In [3]:
import numpy as np
import torch

In [4]:
torch.cuda.is_available()

True

In [5]:
a = torch.IntTensor([1, 1, 2, 3, 4])
a

tensor([1, 1, 2, 3, 4], dtype=torch.int32)

In [6]:
a = torch.tensor([1, 1, 2, 3, 4])
a

tensor([1, 1, 2, 3, 4])

In [7]:
b = torch.IntTensor([1, 1, 4, 5, 6])
a * b

tensor([ 1,  1,  8, 15, 24])

In [8]:
torch.dot(a, b)

RuntimeError: dot : expected both vectors to have same dtype, but found Long and Int

In [9]:
a @ b

RuntimeError: dot : expected both vectors to have same dtype, but found Long and Int

In [10]:
a.size()

torch.Size([5])

In [11]:
a[None, :].shape

torch.Size([1, 5])

In [12]:
a.view(-1, 1).shape

torch.Size([5, 1])

In [13]:
a.T

C:\Users\user\AppData\Local\Temp\ipykernel_10520\2533872927.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3618.)
  a.T


tensor([1, 1, 2, 3, 4])

In [14]:
import pandas as pd

In [ ]:
df = pd.read_csv('iris.data')
df.head()

In [ ]:
torch.Tensor(df.loc[1][:-1].to_numpy().astype("float32"))