In [1]:
%pip install -Uq numpy

Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [59]:
import numpy as np

In [73]:
class Matrix:
    def __init__(self, matr: list):
        first_row_size = len(matr[0]) 
        for row in range(1, len(matr)):
            if len(matr[row]) != first_row_size:
                raise ValueError("Wrong matrix dimensions!")     # nuke this shit if matrix dimensions are fucked
        self.matrix = matr
        self.rows = len(self.matrix)
        self.columns = len(self.matrix[0])

    
    def __get__(self):
        return self.matrix
    
    def generate_matrix(rows: int, columns: int) -> 'Matrix':
        return Matrix([[0] * columns for i in range(rows)])

    def T(self):
        result = Matrix.generate_matrix(self.columns, self.rows)
        for row in range(result.rows):
            for column in range(result.columns):
                result.matrix[row][column] = self.matrix[column][row]
        return result

    def __add__(self: 'Matrix', other: 'Matrix|int|float'):
        result = Matrix.generate_matrix(self.rows, self.columns)
        if isinstance(other, Matrix):
            for row in range(self.rows):
                for column in range(self.columns):
                    result.matrix[row][column] = self.matrix[row][column] + other.matrix[row][column]
        else:
            for row in range(self.rows):
                for column in range(self.columns):
                    result.matrix[row][column] = self.matrix[row][column] + other
        return result
    
    def __sub__(self: 'Matrix', other: 'Matrix|int|float'):
        result = Matrix.generate_matrix(self.rows, self.columns)
        if isinstance(other, Matrix):
            for row in range(self.rows):
                for column in range(self.columns):
                    result.matrix[row][column] = self.matrix[row][column] - other.matrix[row][column]
        else:
            for row in range(self.rows):
                for column in range(self.columns):
                    result.matrix[row][column] = self.matrix[row][column] - other
        return result
    
    def __truediv__(self: 'Matrix', other: 'int|float'):
        result = Matrix.generate_matrix(self.rows, self.columns)
        if isinstance(other, Matrix):
            for row in range(self.rows):
                for column in range(self.columns):
                    result.matrix[row][column] = self.matrix[row][column] / other.matrix[row][column]
            return result
        else:
            for row in range(self.rows):
                for column in range(self.columns):
                    result.matrix[row][column] = self.matrix[row][column] / other
            return result
    
    def __mul__(self: 'Matrix', other: 'Matrix|int|float'):
        result = Matrix.generate_matrix(self.rows, self.columns)
        if isinstance(other, Matrix):
            for row in range(self.rows):
                for column in range(self.columns):
                    result.matrix[row][column] = self.matrix[row][column] * other.matrix[row][column]
            return result
        else:
            for row in range(self.rows):
                for column in range(self.columns):
                    result.matrix[row][column] = self.matrix[row][column] * other
            return result
        
    def __matmul__(self: 'Matrix', other: 'Matrix'):
        result = Matrix.generate_matrix(self.rows, other.columns)
        for row in range(result.rows):
            for column in range(result.columns):
                temp: int|float = 0
                for i in range(self.columns):
                    temp += self.matrix[row][i] * other.matrix[i][column]
                result.matrix[row][column] = temp
        return result
    
    def __eq__(self, other: list) -> bool:
        return self.matrix == other


    def __repr__(self) -> str:
        return str(self.matrix)
    
    
    # not working like i hoped for
    def printable(self) -> str:
        result = ""
        for row in range(self.rows):
                result += str(self.matrix[row])
                result += '\n'
        return result


In [74]:
np_matrix1 = np.array([
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
    [11, 22, 33]
])
np_matrix2 = np.array([
    [4, 5, 6],
    [7, 8, 9],
    [77, 12, 12],
    [2, 1, 45]
])

my_matrix1 = Matrix([
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
    [11, 22, 33]
])
my_matrix2 = Matrix([
    [4, 5, 6],
    [7, 8, 9],
    [77, 12, 12],
    [2, 1, 45]
])

In [75]:
my_matrix1

[[1, 1, 1], [1, 2, 3], [11, 12, 13], [11, 22, 33]]

In [76]:
print(np_matrix1 + np_matrix2)
print()
print((my_matrix1 + my_matrix2).printable())

[[ 5  6  7]
 [ 8 10 12]
 [88 24 25]
 [13 23 78]]

[5, 6, 7]
[8, 10, 12]
[88, 24, 25]
[13, 23, 78]



In [77]:
print(np_matrix1 - np_matrix2)
print()
print((my_matrix1 - my_matrix2).printable())

[[ -3  -4  -5]
 [ -6  -6  -6]
 [-66   0   1]
 [  9  21 -12]]

[-3, -4, -5]
[-6, -6, -6]
[-66, 0, 1]
[9, 21, -12]



In [78]:
print(np_matrix1 / 2)
print()
print((my_matrix1 / 2).printable())

[[ 0.5  0.5  0.5]
 [ 0.5  1.   1.5]
 [ 5.5  6.   6.5]
 [ 5.5 11.  16.5]]

[0.5, 0.5, 0.5]
[0.5, 1.0, 1.5]
[5.5, 6.0, 6.5]
[5.5, 11.0, 16.5]



In [79]:
print(np_matrix1 * 3)
print()
print((my_matrix1 * 3).printable())

[[ 3  3  3]
 [ 3  6  9]
 [33 36 39]
 [33 66 99]]

[3, 3, 3]
[3, 6, 9]
[33, 36, 39]
[33, 66, 99]



In [80]:
print(np_matrix1 * np_matrix2)
print()
print((my_matrix1 * my_matrix2).printable())

[[   4    5    6]
 [   7   16   27]
 [ 847  144  156]
 [  22   22 1485]]

[4, 5, 6]
[7, 16, 27]
[847, 144, 156]
[22, 22, 1485]



In [81]:
my_transp = Matrix([[1,2,3,4],[5,6,7,8]])
np_transp = np.array([[1,2,3,4],[5,6,7,8]])
print(my_transp.T().printable())
print(np_transp.transpose())

[1, 5]
[2, 6]
[3, 7]
[4, 8]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [82]:
print(np_matrix1 @ np_matrix2.transpose())
print()
print((my_matrix1 @ my_matrix2.T()).printable())

[[  15   24  101   48]
 [  32   50  137  139]
 [ 182  290 1147  619]
 [ 352  550 1507 1529]]

[15, 24, 101, 48]
[32, 50, 137, 139]
[182, 290, 1147, 619]
[352, 550, 1507, 1529]



In [83]:
my_matrix1 == np_matrix1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [84]:
%pip install -q ipytest pytest

import ipytest
import pytest
ipytest.autoconfig()

Note: you may need to restart the kernel to use updated packages.


In [85]:
%%ipytest

matrix1 = Matrix([
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
    [11, 22, 33]
])
matrix2 = Matrix([
    [4, 5, 6],
    [7, 8, 9],
    [77, 12, 12],
    [2, 1, 45]
])


@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_add_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 + matrix2 == (np.array(matrix1.matrix) + np.array(matrix2.matrix))).all()
    ), 'add section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13.2]])
def test_matrix_add_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 + number == np.array(matrix1.matrix) + number).all()
    ), 'add section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_sub_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 - matrix2 == np.array(matrix1.matrix) - np.array(matrix2.matrix)).all()
    ), 'sub section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 12.2]])    
def test_matrix_sub_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 - number == np.array(matrix1.matrix) - number).all()
    ), 'sub section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1", [matrix1])    
def test_matrix_transpose(matrix1: Matrix):
    assert (
        (matrix1.T() == np.array(matrix1.matrix).T).all()
    ), 'transpose section is not working right'
    
# -----------------------------------------

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_mul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 * matrix2 == np.array(matrix1.matrix) * np.array(matrix2.matrix)).all()
    ), 'mul section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13]])
def test_matrix_mul_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 * number == np.array(matrix1.matrix) * number).all()
    ), 'mul section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])    
def test_matrix_div_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 / matrix2 == np.array(matrix1.matrix) / np.array(matrix2.matrix)).all()
    ), 'div section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 2]])    
def test_matrix_div_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 / number == np.array(matrix1.matrix) / number).all()
    ), 'div section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2.T()]])    
def test_matrix_matmul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert(
        (matrix1 @ matrix2 == np.array(matrix1.matrix) @ np.array(matrix2.matrix)).all()
    ), 'matmul section is not working right, and don\'t forget about T() if needed'
    


..........                                                                                   [100%]
10 passed in 0.02s
